apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helpdesk-ingress
spec:
  rules:
  - http:
      paths:
      - path: /ai
        pathType: Prefix
        backend:
          service:
            name: ai-service
            port:
              number: 80